### ISSUE TITLE
While scrolling in Internert Explorer scrollbar is shaking and jumping ? can u please check this ASAP

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#523] opened 2016-06-20 12:44 UTC
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment] 2016-06-20 12:49
There is no really good way to resolve the jumpy scrolling issue in IE. I would say it is absolutely an IE rendering bug concerning scrolling. Fortunately, the issue is fixed in Edge. Please check the following issue threads about the issue. #160 #435 

Even though the threads are closed, I still welcome any contribution. If you come up with a nice idea, please feel free to let me know.

**Closed by noraesae** 2016-06-20 12:49 UTC

**Comment by rajagopal14** [comment] 2016-06-20 12:57
thank you. Can u pls check this issue also #522
