### ISSUE TITLE
Lock direction while scrolling?

### ISSUE THREAD

**Issue by czak** [noraesae/perfect-scrollbar#407] opened 2015-10-29 10:06 UTC
Is there a way to "lock" the scrolling direction while scrolling?

I have a large table which scrolls both vertically and horizontally.
Using `perfect-scrollbar` and a laptop trackpad I can now scroll in any direction - even diagonally.
This is good for images, but for a table it would be better to "lock" vertical or horizontal direction as soon as I start dragging - so that I can move only vertically or horizontally.

**Comment by zenorocha** [comment] 2015-11-12 02:01
+1

**Comment by zenorocha** [comment] 2015-11-16 00:14
I have multiple columns with vertical scrolls and a horizontal scroll to move the whole page.

When I move the vertical columns it works nice. The problem is that when I move horizontally using a trackpad it also detects the vertical scrolls from each column, causing them to move on a weird way.

Here's a more visual example of what I'm trying to describe.

![Demo](https://cloud.githubusercontent.com/assets/398893/11172014/d6150344-8bc3-11e5-91d7-41e2a6d0ef4d.gif)

If there was a way to detect a horizontal scroll and then lock any other vertical scroll, I guess that would fix the problem.

What do you think?

**Comment by zenorocha** [comment] 2015-11-26 19:11
Any news on this? Here's a minimal JSFiddle that shows the problem: http://jsfiddle.net/zenorocha/wb6b635q/

**Comment by czak** [comment] 2015-11-27 11:41
My personal use case is simpler than yours (just a single large table), so I kind of got used to it.
I'm not currently pursuing this addition.

**Comment by DanielApt** [comment] 2015-12-02 23:53
@zenorocha this might be as straightforward as I thought. Blocking the scrolling requires some kind of relationship between child and parent scroll components. I need to do some further delving in to to figure out the right approach.

**Comment by DanielApt** [comment] 2015-12-02 23:54
If anyone has an idea how to start tackling this, I'd love to hear it.

**Comment by noraesae** [comment] 2016-11-06 13:48
I think this is a little overkill for what PS should do, because distinguishing scroll axis among containers may be difficult to implement and expensive on performance, expecially on `wheel` events. I'm afraid I close this issue here, but if anybody has a nice solution about this issue, please feel free to upload an issue or PR.

**Closed by noraesae** 2016-11-06 13:48 UTC
Labels: help wanted
