### ISSUE TITLE
When used inside Bootstrap Dropdown, dropdown gets hidden by scrolling using side rail (click & drag)

### ISSUE THREAD

**Issue by tarunmangukiya** [noraesae/perfect-scrollbar#526] opened 2016-06-28 08:35 UTC
I am using perfect-scrollbar inside Boostrap Dropdown, like in my case for showing notifications in a dropdown using perfect scrollbar.

When user clicks on side rail (y-rail) and scrolls using that rail, on leaving mouse button the dropdown menu gets hidden. The scroll happens but just dropdown hide event is getting fired.

Scroll using mouse scroll wheel and touchpad multiple gesture works fine.

Seems like issue of propagation of click/release event. 

Hope someone can help.

**Comment by noraesae** [comment] 2016-07-12 17:23
I'm not sure if it's an issue of PS or Bootstrap Dropdown. Can you provide a fiddle to reproduce the problem? You can start from forking basic fiddles.

- Vanilla JS: https://jsfiddle.net/DanielApt/xv0rrxv3/
- jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/

**Comment by shinygruv3** [comment] 2016-07-18 20:41
I'm seeing the same issue...ostensibly due to mouseup propagation when dragging the scrollbar on the dropdown. Here's a fiddle: https://fiddle.jshell.net/shinygruv3/auok2bg8/5/

**Comment by tarunmangukiya** [comment] 2016-07-20 07:35
@shinygruv3 I am facing the same issue. @noraesae Please find fiddle by him.

**Comment by chavishindler** [comment] 2016-07-27 11:55
hi,
I have the same issue with uib-dropdown.
It seems the fix for the bug is that you should add to perfect-scrollbar library an onclick event to ps-scrollbar-x-rail and ps-scrollbar-y-rail that invoke event.stopPropagation to prevent the default dropdown click behaviour which hide the dropdown.

waiting to your reply, thanks.

**Comment by shinygruv3** [comment] 2016-07-28 20:27
I believe the code does invoke event.stopPropagation for both the rail and the bar. I've also noticed that the dropdown does not close on-mouse-up 100% of the time...at least not in my actual project. The fiddle example seems to always close on-mouse-up.

**Comment by shinygruv3** [comment] 2016-08-01 16:08
For others on this thread, I fixed this by tweaking how I use uib-dropdown: set *auto-close*="disabled" and explicitly control *is-open*. Given that the scroll rail/bar are siblings to the list items (which also handle click events), I don't think there's a way for perfect-scrollbar to fully control event propagation to the parent container.

**Comment by chavishindler** [comment] 2016-08-09 10:39
Why can not perfect-scrollbar control event propagation of the parent container?
If I add a button in the uib-dropdown and on-click I invoke event.stopPropagation the dropdown is not closed. I think it should behave the same in perfect-scrollbar.
**@noraesae** can you add this behaviour?

thanks.

**Comment by shinygruv3** [comment] 2016-08-09 19:05
@chavishindler 

Hmm. My thought was that the parent container (i.e. ul) should not stop-propagation to children because the dropdown li elements need to react to click...and that scroll rail/bar trying to prevent propagation won't affect the siblings...which still need to react to the click. 

But now I'm wondering if this whole thing is a side-effect of the dropdown responding to onblur.

**Comment by chavishindler** [comment] 2016-08-10 09:49
If I add the on-click to all the perfect-scrollbar that wraps my list - it should prevent the children behaviour.
But I think if I add the onclick event only to ps-scrollbar-y - it should not prevent my list behaviour because the ps-scrollbar-y is not a parent of the ul or li.

Here is your jsFiddle example source code - you can see the ps-scrollbar-y is not parent of the li list:

```<ul class="dropdown-menu scroll-container ps-container ps-theme-default ps-active-y" role="menu" data-ps-id="e9e5697b-faf9-87e9-d8e6-35e15ccc7c77">
                   <li><a href="#">Item 1</a></li>
                   <li><a href="#">Another item</a></li>
                   <li><a href="#">This is a longer item that will not fit properly</a></li>
                   <li><a href="#">Item 2</a></li>
                   <li><a href="#">Item 3</a></li>
                   <li><a href="#">Item 4</a></li>
                   <li><a href="#">Item 5</a></li>
                   <li><a href="#">Item 6</a></li>
                   <li><a href="#">Item 7</a></li>
                   <li><a href="#">Item 8</a></li>
                   <li><a href="#">Item 9</a></li>
                   <li><a href="#">Item 10</a></li>
                 <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: -121px;">
                     <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
                 </div>
                 <div class="ps-scrollbar-y-rail" style="top: 124px; right: 3px; height: 198px;">
                       <div class="ps-scrollbar-y" tabindex="0" style="top: 77px; height: 121px;"></div>
                  </div>
</ul>```


here is an example of div that onClick event doesnt close the dropdown: https://fiddle.jshell.net/auok2bg8/6/

**Comment by shinygruv3** [comment] 2016-08-10 15:06
@chavishindler - I'm a bit confused. The example for the link you provide does result in the menu closing when you click-on or click-and-drag the scrollbar. 

Something I noticed yesterday...the scrollbar (i.e. ps-scrollbar-x, ps-scrollbar-y) is subscribed to the 'click' event, And the handler calls event.stopPropagation(). However, the handler is never invoked. The same is true for the focus & blur events. @noraesae any ideas?

**Comment by noraesae** [comment] 2016-10-18 01:53
This is because `mouseup` is not handled by scrollbar elements, but by `window`. It is implemented like this because it's very natural for users to keep mousedown and scroll while dragging outside. Because `window` handles the event, it cannot be fixed by `stopPropagation` or `preventDefault`.

The quick fix for this may be by fixing Bootstrap Dropdown not to close its menu when there's `ps-in-scrolling-x` or `ps-in-scrolling-y` class set on the container. It may be done easily if there is any custom event handler provided by Bootstrap Dropdown. Unless, it should be done by manually fixing its source.

Unfortunately, this is not something PS can fix, so I close this issue here. I'm sorry that I cannot help so much, and thank you very much for the report.

**Closed by noraesae** 2016-10-18 01:53 UTC
