### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of null

### ISSUE THREAD

**Issue by nethulap** [noraesae/perfect-scrollbar#330] opened 2015-05-05 01:28 UTC
My application is a single page angular app using the angular-perfect-scrollbar. when the app is in mobile mode(app running on mobile emulator) i get this error "Uncaught TypeError: Cannot read property 'css' of null". The error is repeated many times as if its in infinite loop until i refresh the page.

![scrollbar_error](https://cloud.githubusercontent.com/assets/7296306/7465739/bc2c232e-f319-11e4-9330-d07022858869.png)

The following code is used in many places of the application.
<div perfect-scrollbar id="scrollid" class="scroller" include-padding="true" always-visible-y="true" refresh-on-change="myArray" style="height: 350px" min-scrollbar-length="25">

No error when the app is in desktop mode.

Is there a solution for this issue?

**Comment by MaximSaraev** [comment] 2015-05-14 09:53
I have almost the same issue on Chrome (emulation iPad mode). And thanks for the good scroll, I expected that you find solution for this problem soon.

**Comment by noraesae** [comment] 2015-06-22 12:59
Hi, sorry for the late response. Actually, I heard about this problem quite many times, but still nobody could suggest a fiddle or code reproducing the bug. I suppose it is occasional. I've also personally never seen this. If you can provide the fiddle, it helps me to narrow down the problem a lot.

Thanks!

**Comment by noraesae** [comment] 2015-07-14 03:44
By 6c642d8a478ce231aad98aee7f6cd541cac816d2, the plugin will return early if there's no proper instance. I'm not particularly sure it fixes this issue as well, but I've no idea if there's any other part a null-check should be added.

If there's further problem, please feel free to open an issue.

Thanks.

**Comment by jigar029** [comment] 2016-01-18 22:16
I am using angular directive for perfect scrollbar and with Chrome Emulator, I am getting same error. Does anyone have solution to remove these errors with use of Angular directive? Any help will be appreciated.

**Comment by DanielApt** [comment] 2016-01-29 10:03
Seems like we're still having this issue. @jigar029, which version are you using?

**Comment by jigar029** [comment] 2016-01-29 16:11
@DanielApt : Thanks for opening issue again and making it active. I am using v0.6.10 for perfect-angular-scrollbar. One thing i found with this directive is, it's failing on destroying the scrollbar either on refresh on resize or orientation change on mobile devices while updating it. If I am removing function which destroy it, i am not seeing these errors at all. But this is not the way it should work. See $destroy function here: 
`$elem.bind('$destroy', function() {
        jqWindow.off('resize', update);
        $elem.perfectScrollbar('destroy');
      });`

**Comment by jigar029** [comment] 2016-01-29 16:13
Again, I am on older version because I am using older version of angular (v1.3.10) in my application.

**Comment by DanielApt** [comment] 2016-01-29 16:18
Which project are you using for angular? Is it [angular-perfect-scrollbar](https://github.com/itsdrewmiller/angular-perfect-scrollbar)? This project is not maintained by the original, nor us.

This actually ties in with https://github.com/noraesae/perfect-scrollbar/issues/442

Could you maybe attempt to use the most recent version of perfect-scrollbar in your project? If you could share an example where we can reproduce the bug, that would be great.

**Comment by jigar029** [comment] 2016-02-01 19:24
Well, seems like changing version and upgrading from V 0.4.11 to V 0.6.10 fixed this issue. I am not getting this error anymore. Thanks for your help @DanielApt . You may want to close this thread.

**Comment by DanielApt** [comment] 2016-02-01 23:09
Thanks for keeping me posted @jigar029. As per your suggestion I'll be closing this thread.

**Closed by DanielApt** 2016-02-01 23:09 UTC
