### ISSUE TITLE
It is not perfect 

### ISSUE THREAD

**Issue by xDaizu** [noraesae/perfect-scrollbar#445] opened 2016-01-25 13:35 UTC
How can it be "*perfect*" if it doesn't have an option to **automatically update itself** when the container changes dinamically? ;P

But no, seriously...

**Comment by noraesae** [comment] 2016-01-25 14:16
Hi, thank you for your interest and feedback on the plugin :smile: 

Yes, I also think that it would be perfectly nice if it can automatically update itself when needed. But the problem is how it's done. In JavaScript, it is neither easy nor cheap to detect resizing. There is a [`resize`](https://developer.mozilla.org/en-US/docs/Web/Events/resize) event, but it is only for `window`. Most of the libraries do detect the change by checking the size in every interval, which I don't really want to do. It is not only expensive, but dangerous(what if the element is removed without unregistering the interval handler?).

So, I concluded to use the current manually update because who knows when to update the scrollbars is not the plugin, but a programmer. Only a programmer can know when is the most efficient moment to update the scrollbars, without any expensive handler and resource waste. I guess, at least for the time being, it is the best solution.

However, fortunately, there are some movements to handle the issue, including #268. Currently I don't really have time to look into the issue, but it may(or may not) be helpful. I close this issue now, but if there is another effective way, please feel free to open an issue and suggest it.

I'm really sorry that I cannot help so much for your need, and thanks again!

**Closed by noraesae** 2016-01-25 14:16 UTC
