### ISSUE TITLE
onClick scrollTop bug in touch mode

### ISSUE THREAD

**Issue by nowseemee** [noraesae/perfect-scrollbar#466] opened 2016-02-25 15:23 UTC
Salute,

when I am on a touch device or turn on emulation in chrome, I experience a bug.

Load the example with touch enabled and tap on the container:
https://jsfiddle.net/f4c3ggv7/1/

It will scroll to the desired position and immediately jump back to top. If you first touch scroll then click the container, all smooth. 

I forked the repo and commited a fix which might very well be a monkey patch but worked for me.
https://github.com/nowseemee/perfect-scrollbar/commit/a6d9d837d34cf32c80052656ccc84cb99328ebfc

I am interested in your input on this problem.

**Comment by DanielApt** [comment] 2016-03-29 22:01
Hi @nowseemee,

I've now had the chance to look at your issue.

This has nothing to do with perfect scrollbar. What you are discussing is how the mobile browser converts *taps* and *swipes* in to *clicks*.

A quick *tap* gets read as a `click` by the browser. If you touch and scroll (basically a *swipe*) then the browser will not consider that gesture a `click`, but rather it triggers `touchstart` event.

As your event handler is bound to the `click` event, it will only call the handler when the browser deems that the touch gesture is a click.

As this is not caused by perfect scrollbar, I'm closing this issue.

**Closed by DanielApt** 2016-03-29 22:01 UTC

**Comment by dietergeerts** [comment] 2016-09-23 07:59
Having no click handler, or anything special, just included the perfect-scrollbar with default options, and I experience this on ipad (safari). So it should be opened again.
